# name: Deploy CI/CD to Servers
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing deploy to server using remote ssh key
#         uses: appleboy/ssh-action@master
#         with:
#           host: "46.250.227.243"
#           username: "dhomanhuri"
#           password: "@Kucing8"
#           port: "22"
#           script: |
#             cd /home/dhomanhuri/JejakiPanel
#             git stash
#             git pull
#             docker-compose up -d --build
